name = "hex-poly-fp"
defaultTargets = ["HexPolyFp"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "0e9bc2960cb36fea9cb8766f6deaff347e340915"

[[require]]
name = "HexModArith"
git = "https://github.com/leanprover/hex-mod-arith.git"
rev = "f596fb8e046e187e039993747e34e4d4337b0cef"

[[lean_lib]]
name = "HexPolyFp"
