name = "hex-poly-fp"
defaultTargets = ["HexPolyFp"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "104a2b0c00eedf0ecab222c1a977dd53dbaa9bb3"

[[require]]
name = "HexModArith"
git = "https://github.com/leanprover/hex-mod-arith.git"
rev = "d8b58a99b84aa1e9a3653b5c939c4047ee0b670c"

[[lean_lib]]
name = "HexPolyFp"
