name = "hex-poly-fp"
defaultTargets = ["HexPolyFp"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPoly"
git = "https://github.com/leanprover/hex-poly.git"
rev = "1f7f31c7733ee5f0fa30d4a376adfa5125895c29"

[[require]]
name = "HexModArith"
git = "https://github.com/leanprover/hex-mod-arith.git"
rev = "67c1559800bc1f62622165d3fe5d6d346661539d"

[[lean_lib]]
name = "HexPolyFp"
precompileModules = true
